											//WELCOME TO THE PART 2

// IN THIS PART WE WILL SEE HOW TO USE window.alert() IN JAVASCRIPT
// THE window.alert() or the alert method in javascript CAN BE USED TO DISPLAY A 
// VISUAL ALERT BOX ON THE SCREEN. THUS WE CAN USE IT TO DISPLAY SOME MESSAGE THAT YOU WANT THE USER TO SEE
// ON YOUR WEBSITE
//THE ALERT METHOD PARAMETER IS SHOWN TO THE USER IN FORM OF PLAIN TEXT
// LETS SEE THE CODE

//window.alert(message to be printed)

// so this is the syntax to use it 
// We also know that window is a global object in nature, so you can only use alert in short
// alert(message to be printed) so this can be used in short 
// lets see an example
window.alert('Hi, I am BRAINTOON: STATEMENT 1');
//LETS RUN IT 
// SO IT DISPLAYS A POP UP AS SHOWN. IT WILL WORK IN SAME WAY IN BROWSERS CONSOLE TOO
// IN SHORT
alert('PLEASE SUBSCRIBE THE CHANNEL: STATEMENT 2');
// SO LETS RUN THIS BOTH WILL RESULT IN MAKING OF SIMILAR POPUP DIALOG BOXES 
// SO AS SHOWN YOU CAN USE THE SHORT FORM TOO
// SO WINDOW.ALERT CAN HELP YOU TO GIVE A MESSAGE TO THE USER ON YOUR WEBSITE. SOMETIMES YOU CAN USE IT TO ALERT THE USER
// FOR EXAMPLE: YOU WILL BE REDIRECTED TO OTHER SITE ETC. MESSAGES
// ALSO NOTE THAT ALERT METHOD IS PROPERTY OF window OBJECT, AND ALL PROPERTIES OF WINDOW OBJECT ARE GLOBAL VARIABLES
// SO WE CAN USE alert as a global variable and thus we need not mention propert window infront of it
// so you can use alert() instead of window.alert()
// ALSO NOTE THAT THE CODE AFTER ALERT WILL NOT BE EXECUTED UNTILL THE ALER DIALOG BOX IS RESPONDED
// LETS SEE AN EXAMPLE
window.alert('CLOSE ME TO PROCEED TO FURTHER CODE EXECUTION');
console.log("CONGRATS, YOU HAVE PROCEEDED FURTHER NICE");
// SO THIS EXAMPLE WILL SHOW US THAT UNTIL THE ALERT DIALOG BOX IS ANSWERED CODE WILL NOT PROCEED FURTHER
// LETS CHECK IT 
// SO YOU CAN SEE THAT IF YOU DISMISS THE ALERT STATEMENTS ONE BY ONE THEN ONLY YOU CAN MOVE FURTHER
// CLEARLY SEE THIS IMPORTANT POINT 
// GENERALLY IT IS DISCOURAGED TO USE THESE DIALOG BOXES MORE NUMBER TIMES IN A SINGLE WEBSITE
// BECAUSE THEY CAN BECOME AWFUL AND IRRITATING FOR THE USER
// SO USE THE WISELY
// LAST EXAMPLE FOR YOU
alert('GUYS, PLEASE SUBSCRIBE THE CHANNEL IF YOU LIKE IT.');
// ALSO ENCLOSE YOUR MESSAGE IN SINGLE QUOTATION MARKS